Fix #296: support foundry vm
fuzzland/ityfuzz pull request #335
Opened 2023-11-07 06:58 UTC by jacob-chia

2023-11-07 09:30 UTC, jacob-chia commented
![image](https://github.com/fuzzland/ityfuzz/assets/61052369/fad281f5-a63a-433c-ae36-0fe9c01dfd20)

2023-11-08 08:45 UTC, 0xAWM requested changes

2023-11-08 08:45 UTC, 0xAWM commented on tests/presets/cheatcode/Cheatcode.t.sol
> +
(callerMode, msgSender, txOrigin) = vm.readCallers(); 
         assertEq(uint256(callerMode), uint256(VmSafe.CallerMode.None)); 
         assertEq(msgSender, oldSender); 
         assertEq(txOrigin, oldOrigin);

2023-11-08 08:45 UTC, 0xAWM commented on tests/presets/cheatcode/Cheatcode.t.sol
> +        vm.prank(randomAddr, randomAddr);
Using another contract to make sure prank is working:

require(msg.sender==0x100)
require(tx.origin==0x200)

2023-11-09 00:51 UTC, 0xAWM approved these changes

2023-11-09 00:52 UTC, merged