support Dump external call relations
fuzzland/ityfuzz pull request #82
Opened 2023-06-13 11:28 UTC by ByteSecurity

- change args corpus_path to work_dir
- write call relations to work_dir/relations.log

2023-06-15 14:12 UTC, ByteSecurity commented
add oracles:typed_debug(x)

2023-06-15 22:16 UTC, shouc requested changes

2023-06-15 22:16 UTC, shouc commented on src/evm/host.rs
> +            self.relations_file
不应该是 caller --> target吗，你这是(caller1, target1) -->  (caller2, target2)吧

2023-06-16 06:40 UTC, ByteSecurity commented on src/evm/host.rs
> +            self.relations_file
好嘞，已修复

2023-06-27 16:55 UTC, shouc commented
closed in favor of https://github.com/fuzzland/ityfuzz/pull/89

2023-06-27 16:55 UTC, closed without merging